server:
  port: 19090

logging:
  level:
    com.reffics: debug

reffics:
  api:
    logging:
      enable: false
  datasource:
    jdbc-url: jdbc:postgresql://192.168.0.30:5432/groupware
    username: reffics
    password: fpvlrtm1!
    pool-name: reffics-datasource
    minimum-idle: 1
    maximum-pool-size: 1
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  redis:
    host-name: 192.168.0.30
    port: 16379
